#!/bin/bash

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_PATH="${CONFIG_PATH:-$SCRIPT_DIR/config.env}"
LOG_DIR="$SCRIPT_DIR/logs"
LOG_FILE="$LOG_DIR/codex-window-$(date '+%Y-%m-%d').log"
LOCK_DIR="$SCRIPT_DIR/.run-lock"
PROMPT="${CODEX_WINDOW_PROMPT:-Reply exactly: READY}"

mkdir -p "$LOG_DIR"
find "$LOG_DIR" -type f -name '*.log' -mtime +14 -delete 2>/dev/null || true

write_log() {
    local message="$1"
    printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$message" | tee -a "$LOG_FILE"
}

if [ ! -f "$CONFIG_PATH" ]; then
    write_log "FAILED: Config file not found: $CONFIG_PATH. Run install-codex-window-task.sh first."
    exit 1
fi

# config.env is generated by the installer with shell-escaped values only.
# shellcheck disable=SC1090
source "$CONFIG_PATH"

: "${CODEX_PATH:?CODEX_PATH is missing from config.env}"
: "${SCHEDULE:?SCHEDULE is missing from config.env}"
MAX_LATENESS_MINUTES="${MAX_LATENESS_MINUTES:-5}"
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-900}"

if [ ! -e "$CODEX_PATH" ]; then
    write_log "FAILED: Configured Codex executable/script does not exist: $CODEX_PATH"
    exit 1
fi

is_on_time() {
    local now_hour now_minute now_total entry hour minute scheduled_total diff
    now_hour=$((10#$(date '+%H')))
    now_minute=$((10#$(date '+%M')))
    now_total=$((now_hour * 60 + now_minute))

    IFS=',' read -r -a entries <<< "$SCHEDULE"
    for entry in "${entries[@]}"; do
        hour=$((10#${entry%:*}))
        minute=$((10#${entry#*:}))
        scheduled_total=$((hour * 60 + minute))
        diff=$((now_total - scheduled_total))
        if [ "$diff" -lt 0 ]; then
            diff=$((diff + 1440))
        fi
        if [ "$diff" -ge 0 ] && [ "$diff" -le "$MAX_LATENESS_MINUTES" ]; then
            return 0
        fi
    done
    return 1
}

# launchd replays StartCalendarInterval events after wake. For this use case,
# a late replay is harmful because it shifts the 5-hour window. Scheduled runs
# therefore execute only within a small lateness tolerance. Manual runs bypass it.
if [ "${CODEX_WINDOW_SCHEDULED:-0}" = "1" ] && ! is_on_time; then
    write_log "Skipped late launchd activation. Current time is outside the ${MAX_LATENESS_MINUTES}-minute tolerance for schedule: $SCHEDULE"
    exit 0
fi

if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    write_log "Skipped: another Codex window activation is already running."
    exit 0
fi
trap 'rm -rf "$LOCK_DIR"' EXIT INT TERM

TMP_OUTPUT="$(mktemp "${TMPDIR:-/tmp}/codex-window.XXXXXX")"
trap 'rm -f "$TMP_OUTPUT"; rm -rf "$LOCK_DIR"' EXIT INT TERM

write_log "Codex window activation started."
write_log "Using Codex: $CODEX_PATH"

"$CODEX_PATH" exec --skip-git-repo-check --ephemeral --json "$PROMPT" >"$TMP_OUTPUT" 2>&1 &
CODEX_PID=$!
START_SECONDS=$SECONDS
TIMED_OUT=0

while kill -0 "$CODEX_PID" 2>/dev/null; do
    if [ $((SECONDS - START_SECONDS)) -ge "$TIMEOUT_SECONDS" ]; then
        TIMED_OUT=1
        kill "$CODEX_PID" 2>/dev/null || true
        sleep 2
        kill -9 "$CODEX_PID" 2>/dev/null || true
        break
    fi
    sleep 1
done

wait "$CODEX_PID" 2>/dev/null
EXIT_CODE=$?

cat "$TMP_OUTPUT" >> "$LOG_FILE"

if [ "$TIMED_OUT" -eq 1 ]; then
    write_log "FAILED: Codex command exceeded ${TIMEOUT_SECONDS}s and was terminated."
    exit 124
fi

if [ "$EXIT_CODE" -eq 0 ] && grep -Eq '"type"[[:space:]]*:[[:space:]]*"turn\.completed"' "$TMP_OUTPUT"; then
    write_log "Codex window activation completed successfully. exit=$EXIT_CODE"
    exit 0
fi

write_log "FAILED: Codex command did not report turn.completed. exit=$EXIT_CODE"
exit "${EXIT_CODE:-1}"
